### ISSUE TITLE
build: autogen.sh warnings

### ISSUE THREAD

**Issue by charlesarcher** [pmodels/mpich#2365]
```
###########################################################
## Autogenerating required files
###########################################################

Generating a helper maint/Version... done
Updating the README... done
Creating subsys_include.m4... Use of uninitialized value in numeric eq (==) at ./maint/gen_subcfg_m4 line 284.
Use of uninitialized value in numeric eq (==) at ./maint/gen_subcfg_m4 line 295.
done
```

```
Creating the enumeration of logging states into src/include/mpiallstates.h... Warning: State in FUNC_EXIT(a) does not match STATE_DECL() in src/include/rlog_macros.h
Warning: State in FUNC_EXIT(a) does not match STATE_DECL() in src/include/rlog_macros.h
done
Extracting control variables (cvar) ... done
Create or update the Fortran 90 tests derived from the Fortran 77 tests... done
```

**Comment by charlesarcher** [comment]
Tools versions:

```
Checking for autoconf version... >= 2.67
Checking for automake version... >= 1.15
Checking for libtool version... >= 2.4.4
```

**Comment by roblatham00** [comment]
There appear to be no more "uninitialized value" warnings, at least with  perl-5.26.1

The "State in FUNC_EXIT()..." warnings from rlog_macros.h is coming from the perl function 'findStateDecl':  it gets confused by code like this:

```
#define RLOG_PT2PT_FUNC_EXIT_BACK(a)                    \
    if (g_pRLOG)                                        \
    {                                                   \
        RLOGI_LogRecv(g_pRLOG, source, tag, count);     \
        RLOG_PT2PT_FUNC_EXIT(a);                        \
    }
```

In practice there will be a matching STATE_DECL, but because this perl script is looking at preprocessor directives instead of final source, it gets confused.

There is some effort to guard against this: match expressions such as `elsif (/FUNC_ENTER\((.*)\)/ && !/^\#\s*define\s/)` will work for single-line defines but not multi-lines as used in this header

I am making a judgement call that jamming this macro onto one line sacrifices more in readability than is gained by silencing this warming.

**Comment by hzhou** [comment]
That script generates more warnings as today. There is a PR to remove FUNCNAME macros. Once that is committed, that script will generate warnings literally everywhere. I could rewrite that script. However, seems rlog hasn't been working for ages and seems nobody really cared, we might as well disable the rlog and skip that script in autogen.
