### ISSUE TITLE
Move MPIR_CVAR_OFI_USE_PROVIDER to upper layer?

### ISSUE THREAD

**Issue by wesbland** [pmodels/mpich#2482]
`MPIR_CVAR_OFI_USE_PROVIDER` is defined in the CH3 device. Since OFI is also used in the CH4 device, it might make sense to move this to a more common location.

**Comment by hzhou** [comment]
@wesbland You mean the YAML comment block? Since `extractcvars` scans all source files, where does that comment block lives really does not matter as far as the build is concerned.

But I agree with you that having that in ch3 is questionable.

The obvious solution is to move that definition to `src/mpid/common`. However we don't really want to put any ofi-specific C files there as ofi really doesn't belong at ch4 layer. How about `src/mpid/common/cvars.txt`?

In general, how about move all cvars YAML blocks to `cvars.txt` (still in the sub source folder where relevant)? The autogen script can go a little faster as it does not need scan through all source code; the source code can be a little shorter for easier read; we can drop the comment marker and even name them `cvars.yaml` as what it supposed to be. Finally, we'll have better flexibility in organizing the CVARS.

**Comment by wesbland** [comment]
I suppose that's ok, but it does lose the flexibility of submodules being able to define whatever they want without impacting each other (the merge conflicts will be fun in particular).

**Comment by hzhou** [comment]
An alternative solution is to duplicate the CVAR definitions and let cvar scripts check duplications and warn if they are in conflict.
