### ISSUE TITLE
ch4/ofi: improvements to the FI_MULTI_RECV active message processing model

### ISSUE THREAD

**Issue by pkcoff** [pmodels/mpich#2720]
Via the investigation I did for  https://github.com/pmodels/mpich/issues/2689 it is apparent to me that the whole active message processing model using FI_MULTI_RECV is fundamentally broken for auto-progress and offloaded architectures, as well as creating memory footprint problems for the new ch4 mulit-threading utilizing scalable endpoints.  The basic methodology is to post N buffers of M size and repost them as they fill up, and with manual progress and a single thread this methodology is fine as the manual progress engine basically guarantees that the repost of active buffer N will happen before before buffer N+1 has a chance to receive messages, however in a disconnected auto-progress mode or offloading architecture where the receiver can make progress on the incoming message packets in a code flow independant of the reposting there is no guarantee of an available active message buffer to match the incoming FI_MULTI_RECV packet, at best all we can do is make the number of buffers and buffer sizes big enough so this shouldn't happen, but we can't guarantee that it won't.  And make the buffers and buffer sizes large will have a huge impact on scalable endpoint implementations, where these buffers will need to be duplicated for every receive context inside the scalable endpoint.

**Comment by raffenet** [comment]
I'm not sure I'm following the argument here. Won't MPICH still be polling for completions in either progress mode and thus reposting MULTI_RECV buffers once all the messages are consumed?

Also, what are "offloaded architectures" offering in terms of functionality that we need to account for?

**Comment by raffenet** [comment]
I'm pulling out this quote from your issue:
```
however in a disconnected auto-progress mode or offloading architecture where the receiver can make progress on the incoming message packets in a code flow independant of the reposting
```
Isn't the solution to just simply make re-posting part of this flow?

**Comment by pkcoff** [comment]
Yeah, maybe instead of 'fundamentally broken' should be will need changes, if all the am buffers are full the unexpected queue will continue to grow, at some point that will become an issue, I was talking with @mblockso about this today maybe he can comment...

**Comment by mblockso** [comment]
I think it is hardware-specific what happens when all multirecv buffers are exhausted and another packet comes in from the fabric. Some hardware may drop the packet and then go into some kind of flow-control re-transmit mode (how does it maintain order??) and others may just blow up. This could happen if the completion queue is not drained sufficiently fast enough so that the multirecv buffers can be re-posted.  At scale, and with auto progress and/or offload architecture, I think this multirecv exhaustion issue could be a problem.

The bgq provider - being a so-called "on-load" architecture - will malloc unexpected packet structures and copy the data off the fabric for later processing. This is ok ... until you run out of memory.

Paul ran into these multirecv issues at 4096 x 32 ranks scale ... what is going to happen when running 3 million ranks or more? I think that is the concern here. We scaled this AM code higher than it has ever scaled before, but we still didn't scale it very high.

**Comment by pkcoff** [comment]
Discussed with Ken on the call today, nothing should be fundamentally changed to support threading and scalable endpoints, provider needs to deal with the issue of having no available am buffers, will look at tuning (eg number of buffers, size of buffers, provider implementations - eg in the case of BGQ the ratio of polling rfifo to processing completion q is like 8:1 could change that, etc.  https://github.com/pkcoff/OFI-BGQ-BuildEnv/issues/3 )

**Comment by raffenet** [comment]
Were these scaling experiments in the AM-only configuration? Or was this native and the applications were generating lots of non-"native" messages?

**Comment by mblockso** [comment]
Not AM-only .. AM is used for the RMA code and other stuff like large message protocol, sync send acks, etc.  So it really isn't a question of native vs. non-native messages.

**Comment by pkcoff** [comment]
The test that exposed the bugs was a passive rma flood of incoming window locks and unlocks (non-native traffic) to the same rank

**Comment by raffenet** [comment]
Ah, an incoming flood. Sounds similar to behavior that triggered flow control events on Portals 4 in the past. @charlesarcher and @wesbland had proposed some progress loop threshold controls in the past in https://github.com/pmodels/mpich/pull/2361. Would these be useful at all?

**Comment by hzhou** [comment]
This ticket is stale and lack of clear directions for actions. FWIW, it has served the discussion purposes.
