### ISSUE TITLE
ch4: Win allocate shared

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#2853]
Right now much of the `MPI_Win_allocate_shared` functionality is duplicated in `ofi_win.h` and `ch4r_win.h`. It also directly uses POSIX shm interfaces directly, rather than the MPL wrappers. Need to do an overhaul of this to make it more sane.

**Comment by pavanbalaji** [comment]
Is there a reason why `MPI_Win_allocate_shared` needs to be overridden by the netmod at all?  Is there something special the netmod can do about it?  I can understand that the shmmods can do something better (e.g., xpmem).

**Comment by wesbland** [comment]
If you're using `--with-ch4-shm=yes` mode, everything goes through the netmod before it goes to the shmmod. It's possible that the netmod might be handling shared memory too. For instance, OFI is exploring various ways of supporting shared memory. I don't know if they'll be something that we want to use in the future or not, but it's always a possibility.

**Comment by hajimefu** [comment]
Thanks for bringing this up. It has been in a list of RMA cleanup since I was working on it with Lena, but at some point it was dropped from our list.

My preference at this point is to abandon the OFI netmod implementation of `Win_allocate_shared`. In future, if somebody comes up with a netmod-specific optimization, then he/she can implement it.

**Comment by wesbland** [comment]
I don't disagree with this, but I don't think we should remove the ability to have it. For now, it can just be a passthrough.

**Comment by pavanbalaji** [comment]
@wesbland what does "removing the ability to add it" mean?  If we don't add a netmod hook for now, we can always add it later when we need it.

**Comment by wesbland** [comment]
Oh. I thought we were talking about taking out a function that already existed.

**Comment by hajimefu** [comment]
@wesbland Yeah, that was my intention too. Thanks for clarification.

@raffenet Right now CH4R/OFI netmod both use `shm_open(3)` and `mmap(2)`, which are POSIX shm interfaces rather than SysV IPC. Nemesis, however, uses SysV IPC through some wrappers. Are you saying POSIX (`shm_open(3)` and `mmap(2)`) is preferable? We should use them through some (possibly MPL) wrappers, though.

**Comment by pavanbalaji** [comment]
I think this should use `MPL` functions and let `MPL` deal with `mmap` vs. `sysv` vs. whatever other POSIX functionality it wants.  If a shmmod wants to use something else (e.g., xpmem), then it'll need to override that functionality.

**Comment by hajimefu** [comment]
@pavanbalaji yes, you're right.

**Comment by raffenet** [comment]
Looks like sanity has been established, so I'm closing this ticket :tada:
