### ISSUE TITLE
Link error with MPICH 3.2.1 and IBM XLC compilers

### ISSUE THREAD

**Issue by harisubramoni** [pmodels/mpich#3050]
Dear, MPICH developers.

I am hitting the following link time error with MPICH 3.2.1 tarball downloaded from the MPICH site if I configure MPICH to build shared libraries. I do not add –enable-shared/--disable-static, the error does not show up.

I configured MPICH as follows

```
./configure --prefix=$PWD/install-dir CC=xlc_r CXX=xlC_r FC=xlf_r F77=xlf_r --enable-g=all --enable-fast=none --enable-shared --disable-static
```

```
make[2]: Entering directory '/g/g90/subramon/MPICH/mpich-3.2.1'
/bin/sh ./libtool  --tag=CC   --mode=link xlc_r  -g -O0 -static  -o src/env/mpichversion src/env/mpichversion.o lib/libmpi.la  -lpthread
libtool: link: xlc_r -g -O0 -o src/env/mpichversion src/env/mpichversion.o  lib/.libs/libmpi.so -L/g/g90/subramon/MPICH/mpich-3.2.1/src/mpl -lrt -lpthread -Wl,-rpath -Wl,/g/g90/subramon/MPICH/mpich-3.2.1/lib/.libs -Wl,-rpath -Wl,/g/g90/subramon/MPICH/mpich-3.2.1/install-dir/lib
/usr/bin/ld: src/env/mpichversion: hidden symbol `lstat' in /usr/lib64/libc_nonshared.a(lstat.oS) is referenced by DSO
```

Based on an offline discussion with Dr. Pavan Balaji, I was able to get the build to pass if I added "--disable-romio" to the configure line.

*Autotools Info*:

```
autoconf (GNU Autoconf) 2.69
automake (GNU automake) 1.15
libtool (GNU libtool) 2.4.6
```

I’m using IBM `xl/beta-2018.02.22` compilers and this is on an OpenPOWER system (not sure if that makes a difference).

Please let me know if you need any further information.

Thanks,
Hari.

**Comment by pavanbalaji** [comment]
I'm able to reproduce this issue even with GCC, although GCC seems to be more forgiving of the fact that I'm doing static builds of select executables even when the user asked me not to.  So the build does not fail.

Here's my analysis so far:

1. Some executables `cpi`, `mpichversion`, etc., are always built statically.  For `cpi`, this is done to catch symbol visibility issues at build time.  For `mpichversion` and friends, there's no good reason to do that.  So, we should at least remove the forced static builds for those executables, leaving us with `cpi`.

2. Whether `cpi` should be built statically or not is debatable.  I think that should simply be removed.  But even if we decide to leave that static build in, we should check to see if the user disabled static builds and not do that if that's the case.  The below patch should be sufficient for that:

```
git diff
diff --git i/configure.ac w/configure.ac
index 90e9edfccd50..639517ab22eb 100644
--- i/configure.ac
+++ w/configure.ac
@@ -5411,8 +5411,10 @@ AC_SUBST(MPI_MAX_ERROR_STRING)
 # Get the value of libtool_static_flag
 if test ! -z "$MPID_LIBTOOL_STATIC_FLAG" ; then
    mpich_libtool_static_flag="$MPID_LIBTOOL_STATIC_FLAG"
-else
+elif test "$enable_static" = "yes" ; then
    mpich_libtool_static_flag="-static"
+else
+   mpich_libtool_static_flag=
 fi
 AC_SUBST([mpich_libtool_static_flag])
```

@harisubramoni can you try the above patch to see if it works for you?

3. That leaves us with the case where the user enable static builds, but the system does not support them (e.g., the system above).  In such cases, my guess is that we ended up confusing libtool by first saying that we do not want static libraries (by passing `--disable-static`) and then force-feeding `-static` to the build of some executables.  If that's true, then the above patch should fix this issue too.

4. This will, however, not fix the issue if the user explicitly passes the `-static` flag to `mpicc`.  Would that be a user error?  Or should mpich explicitly disable that option since it does not have static libraries built?

**Comment by pavanbalaji** [comment]
I've created PR#3055 for this.

**Comment by harisubramoni** [comment]
Hi, Pavan.

I applied the patch to configure.ac, and rebuilt the entire library. The following is the modified snippet of code from configure.ac

# Get the value of libtool_static_flag
if test ! -z "$MPID_LIBTOOL_STATIC_FLAG" ; then
   mpich_libtool_static_flag="$MPID_LIBTOOL_STATIC_FLAG"
elif test "$enable_static" = "yes" ; then
   mpich_libtool_static_flag="-static"
else
   mpich_libtool_static_flag=
fi
AC_SUBST([mpich_libtool_static_flag])

I used a shared library (without the --disable-romio flag) build assuming that the patch will fix it. However, I still see the issue.

./autogen.sh; ./configure --prefix=$PWD/install-dir CC=xlc_r CXX=xlC_r FC=xlf_r F77=xlf_r --enable-g=all --enable-fast=none --enable-shared --disable-static; make clean; make -j 20

make[2]: Entering directory '/g/g90/subramon/MPICH/mpich-3.2.1'
/bin/sh ./libtool  --tag=CC   --mode=link xlc_r  -g -O0   -o src/env/mpichversion src/env/mpichversion.o lib/libmpi.la  -lpthread
libtool: link: xlc_r -g -O0 -o src/env/.libs/mpichversion src/env/mpichversion.o  lib/.libs/libmpi.so -L/g/g90/subramon/MPICH/mpich-3.2.1/src/mpl -lrt -lpthread -Wl,-rpath -Wl,/g/g90/subramon/MPICH/mpich-3.2.1/install-dir/lib
/usr/bin/ld: src/env/.libs/mpichversion: hidden symbol `lstat' in /usr/lib64/libc_nonshared.a(lstat.oS) is referenced by DSO
/usr/bin/ld: final link failed: Bad value
make[2]: *** [Makefile:19690: src/env/mpichversion] Error 1
make[2]: Leaving directory '/g/g90/subramon/MPICH/mpich-3.2.1'
make[1]: *** [Makefile:38603: all-recursive] Error 1
make[1]: Leaving directory '/g/g90/subramon/MPICH/mpich-3.2.1'
make: *** [Makefile:10332: all] Error 2

Could you please let me know if I did something wrong?

Thx,
Hari.

**Comment by pavanbalaji** [comment]
So libtool is no longer using the `-static` flag, which is a good thing.  But somehow, the linker seems to be using `-static` as default, so essentially forcing the link step to use `/usr/lib64/libc_nonshared.a` instead of `/usr/lib64/libc.so`.

Can you check if `libc_nonshared.a` and/or `libc.so` contain the `lstat` symbol?  `nm libc.so`.

**Comment by pavanbalaji** [comment]
I found this reference on the web: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=195847

**Comment by pavanbalaji** [comment]
Can you check if the binutils version is too old?

**Comment by harisubramoni** [comment]
Hi, Pavan.

The non-shared version seems to have it.

```
$ nm /usr/lib64/libc.so.6 | grep lstat
000000000012fa20 W pthread_setcancelstate

$ nm /usr/lib64/libc_nonshared.a | grep lstat
lstat.oS:
0000000000000000 T __lstat
0000000000000000 W lstat
lstat64.oS:
0000000000000000 T lstat64

$ nm /usr/lib64/libc.so | grep lstat
nm: /usr/lib64/libc.so: File format not recognized
```

The binutils seems to be `2.25.1-22.base.el7` which is newer than what the bug report mentions `2.13.90.0.18`.

```
$ ld --version
GNU ld version 2.25.1-22.base.el7
Copyright (C) 2014 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

$ as --version
GNU assembler version 2.25.1-22.base.el7
Copyright (C) 2014 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `ppc64le-redhat-linux'.
```

Please let me know if any other information is required.

Thx,
Hari.

**Comment by harisubramoni** [comment]
Hi, Guys.

Any luck on this issue?

Thx,
Hari.

**Comment by raffenet** [comment]
@yfguo builds somewhat frequently with XL. Hoping he can share some insight. Remember we have some non-BG/Q IBM machines in JLSE to test one, as well.

**Comment by harisubramoni** [comment]
I can confirm that the patch @yfguo created fixes the issue.
