### ISSUE TITLE
VCI pool infrastructure

### ISSUE THREAD

**Issue by minsii** [pmodels/mpich#3356]
<h3>Design Summary</h3>

VCI (Virtual Communication Interface) pool is to a generic API to manage the network or shm communication resource assignment:

- We define different attributes of VCI (i.e., `resource`, `type`, `property` in this proposal) based on the need of CH4.
- The netmod/shmmod internally manages the actual VCI allocation (i.e., some attributes might not be available)
- The netmod/shmmod exposes `vci_alloc` and `vci_free` interfaces to allow CH4 (the user) to request for VCI with different attributes at comm|win|file creation time.
- CH4 requests for a VCI with some requirements through the `vci_alloc` API.  If a specific VCI resource is not available (e.g., a thread tries to get an `exclusive VCI`, but no new VCI can be created due to limited hardware resource), CH4 could request for a `generic VCI` as fallback.
- CH4 may call `vci_free` to release the VCI at comm|win|file free time.

<h3>API Definition</h3>

- Functions Definition:
```
MPIDI_NM_vci_alloc(int resource, int type, int properties,  MPIDI_VCI_t * vci);
MPIDI_NM_vci_free(MPIDI_VCI_t  vci);
MPIDI_SHM_vci_alloc(int resource, int type, int properties,  MPIDI_VCI_t * vci);
MPIDI_SHM_vci_free(MPIDI_VCI_t  vci);
```

- Parameter Description:
```
int resource (INPUT, required):
MPIDI_VCI_TX, MPIDI_VCI_RX

int types (INPUT, required):
MPIDI_VCI_SHARED, MPIDI_VCI_EXCLUSIVE

int properties (INPUT, optional, zero if empty):
MPIDI_VCI_TAGGED_ORDERED, MPIDI_VCI_TAGGED_UNORDERED
MPIDI_VCI_RAR, MPIDI_VCI_WAR, MPIDI_VCI_RAW, MPIDI_VCI_WAW

Example: 
resource = MPIDI_VCI_TX | MPIDI_VCI_RX
type = MPIDI_VCI_SHARED
properties = MPIDI_VCI_TAGGED_ORDERED | MPIDI_VCI_WAR 
```

Slides including design details:
[multi-property-vni-2018-10-02.pptx](https://github.com/pmodels/mpich/files/2446936/multi-property-vni-2018-10-02.pptx)
[multi-property-vci-2019-01-21.pptx](https://github.com/pmodels/mpich/files/2783454/multi-property-vci-2019-01-21.pptx)

**Comment by shawnccx** [comment]
One question, the slides said `The netmod can define internal pools based on the hardware support`. Does this allow netmod to pre-allocate resource in initialization?

**Comment by minsii** [comment]
You can, but I think we prefer allocation on demand. You never know which VNI type the user program wants.

**Comment by minsii** [comment]
The internal pools can be statically defined at initialization time, but each of the pools is empty.

**Comment by shawnccx** [comment]
I prefer allocation on demand (on the fly) also. But if performance matters, then we should compromise to pre-allocation.

Using pre-allocation, the internals pools are empty at initialization(), we just allocate some number of resource, and assign them to specific internal pool on demand.

**Comment by shawnccx** [comment]
@hajimefu What do you think?

**Comment by shawnccx** [comment]
OFI scalable endpoint VS normal endpoint. SEP needs to specify how many TX/RX in initialization, while normal EP can be created anytime.

**Comment by minsii** [comment]
Scalable EP and normal EP is actually another topic IMO. When does SEP outperforms EP ? It looks like SEP is beneficial only for multithreaded case. Is it true ?

**Comment by shawnccx** [comment]
I agree, it is all about resource, not VNI, another topic. I'm just double checking about pre-allocation of resource.  

> When does SEP outperforms EP ? It looks like SEP is beneficial only for multithreaded case. Is it true ?

I think so.

**Comment by hajimefu** [comment]
@minsii I have two questions.
1. Who defines `MAX_VNI_NUM`?
2. Currently we are using an integer index to specify a particular VNI, but with this new design we are going to use a pointer for a VNI?

**Comment by hajimefu** [comment]
@minsii Thanks. So I assume netmod can define its own CVAR(s) and let the user specify how many contexts to allocate, then tell `MAX_VNI_NUM` to CH4. I think this is somewhat similar to what we've been already doing in `master`.

**Comment by hajimefu** [comment]
@minsii Assuming my previous comment is right, we think this proposal looks good.

**Comment by minsii** [comment]
@hajimefu Is the OFI CVAR(s) mainly used for SEP creation (e.g., specifying the number of TX/RX) ? 

If you agree, I think we could delete the separate SEP and STX design in `ofi_win.h`. We should let CH4 to request any additional resource for a specific window when needed.

**Comment by hajimefu** [comment]
@minsii Yes. The biggest challenge for OFI scalable endpoint is that it needs to know the maximum number of contexts at the init time (=when calling `fi_scalable_ep()`. Note that this is not individual context creation e.g. `fi_tx_context()`).

Once this new VNI design is established, the current SEP/STX creation logic (especially the ones for RMA) will migrate to the new CH4 VNI design.

**Comment by pavanbalaji** [comment]
Sorry, I'm joining late on this discussion.  A few comments:

1. Can this be generalized a bit to work with shared memory as well?

2. `MPIDI_VNI_t` was an opaque handle instead of an `int`, because the netmod might choose to maintain multiple pools, in which case, pointers might be more convenient for that netmod.  If a netmod uses a single pool, then it can simply typedef `MPIDI_VNI_t` to `int` if it likes.

3. For this discussion, it'll be good to decouple the netmod's job with CH4's job.  The netmod only deals with allocating and managing the actual VNI resources.  Whether it does that allocation statically or dynamically is irrelevant for CH4.  It is a valid netmod implementation to allow CH4 to allocate a pool without immediately allocating any of the internal VNIs (those can be done on-demand, if desired).

4. It is a valid netmod implementation to not support any VNI-specialization.  It is also a valid netmod implementation to support a single VNI.  That way, any attempt to allocate an exclusive VNI will fail.  Any specialization requests for VNIs will simply be ignored and the single generic VNI will be returned for all allocations.

**Comment by pavanbalaji** [comment]
What's the relationship between this and #2391 ?  Sounds like this issue should be merged there as one of the list items?

**Comment by rzambre** [comment]
The current alloc and free API relates to allocating and freeing a VNI from the pool. There is no API to allocate and free the pool itself. @pavanbalaji does bullet 3 require that we need an API for CH4 to instruct the netmod to allocate the pool itself?
> It is a valid netmod implementation to allow CH4 to allocate a pool without immediately allocating any of the internal VNIs (those can be done on-demand, if desired).

**Comment by pavanbalaji** [comment]
I guess we should revisit this API to think about whether we need to have more than one pool at all.

If we use the simple assumption that there's a single pool (which can internally have multiple types of VNIs), then this pool will simply get setup at init time and no separate pool allocation API would be needed.  Our API will look something like:  `MPIDI_NM_VNI_alloc`, `MPIDI_NM_VNI_free`, `MPIDI_SHM_VNI_alloc` and `MPIDI_SHM_VNI_free`.

@minsii?

**Comment by minsii** [comment]
There are two kinds of pools in the original proposal: `netmod internal pools`  and the global `MPIDI_NM_vni_pool` variable.
- The `internal pools` are for managing the status of different types of VNI resource (e.g., each pool can be a linked list of a specific type of VNI such as `<TX, SHARED, TAGGED_ORDERED>`) for performance optimization. I do not think it is necessary to expose the `internal pool creation` to CH4. A netmod can just internally create it when necessary (e.g., if the netmod supports many different types of VNIs, separating them into different pool might be more efficient when searching a matching VNI resource). Maybe we want to rename "internal pool" to avoid confusing.

- The `MPIDI_NM_vni_pool` is a single global variable. Thus, `MPIDI_NM_vni_pool.alloc(resource, type, properties, &vni)` allocates a VNI, but not a pool. I prefer the new API `MPIDI_NM_VNI_alloc|free`, as it is less confusing.

**Comment by pavanbalaji** [comment]
@minsii I don't think there's any confusion about the two types of pools.  We are only referring to the CH4-visible pool.  The question here is simple: since there's only one `MPIDI_NM_vni_pool`, why bother giving it a variable name at all?  Instead the function `MPIDI_NM_vni_alloc` will simply give a VNI.

**Comment by minsii** [comment]
> @minsii I don't think there's any confusion about the two types of pools. We are only referring to the CH4-visible pool. The question here is simple: since there's only one MPIDI_NM_vni_pool, why bother giving it a variable name at all? Instead the function MPIDI_NM_vni_alloc will simply give a VNI.
Agree

**Comment by pavanbalaji** [comment]
Can you update the API accordingly?  Please also see my comment about unifying it with shmmods too.

**Comment by minsii** [comment]
Unlike netmod, we may support two shmmods at the same runtime (e.g., `xpmem, posix`). CH4 should not worry about which shmmod is used for a message, and a VNI resource (e.g., a CH4 comm) may also want to use both `xpmem` and `posix` for different message sizes. Then, how do we consider the mapping between a SHM VNI and the actual resource ? Should the SHM VNI be managed in the SHM glue layer ?

**Comment by pavanbalaji** [comment]
I think it's best if the VNI resources are managed by the glue layer and each generic VNI have identical set of resources from each of the shmmods.  In practice, only POSIX will likely have large resources (the actual shared memory buffers), while the others might not have too many resources.

**Comment by minsii** [comment]
Updated the design slides (attached in the top comment):
- Renamed API (e.g., `MPIDI_NM_vni_pool.alloc|free` -> `MPIDI_NM_vni_alloc|free`)
- Extended API to cover SHM VNI
- Clarified the `MPIDI_VNI_t` opaque handle

**Comment by minsii** [comment]
Yes, I agree that we should merge this issue with #2391

**Comment by pavanbalaji** [comment]
> I prefer allocation on demand (on the fly) also. But if performance matters, then we should compromise to pre-allocation.

I want to address this comment more directly.  I agree that dynamic allocation cost can be high.  It's not just the cost of the allocation of the VNI, but also the exchange of the VNI information with other processes -- this would typically be done over PMI, although one can imagine a model where the global VNI is used for exchanging this information too.

Since there's no global communication call at that time, this can be especially tricky.  I'd recommend starting with a static allocation for the production code and @rzambre and others can investigate how to do this dynamically as a research topic.

**Comment by hajimefu** [comment]
A few thoughts:

1. Dynamic allocation of VNI poses several challenges. For example, if a sender process and a receiver process dynamically allocate a VNI, both have to somehow agree on which receiver-side VNI is used to receive a message. I think @pavanbalaji  implied this problem in the [previous comment](
https://github.com/pmodels/mpich/issues/3356#issuecomment-456437319). I agree that we should begin with static allocation.
2. Multi-VCI for shmmods: I guess we'll need to change the order of some steps. In the current code in master, first we take a VNI lock, then enqueue to the work queue, and then on the worker (dequeuer) side, we look at AV entry to figure out the destination (NM or SHM -- in *_unsafe functions). In order to consider multiple VCIs in SHM and NM, this order has to be changed; first look at AV entry to see whether if it goes to NM or SHM, then determine the VCI to use, lock VCI, and finally enqueue. Is this something @halimamer is working on?
3. This might be an independent topic but from the slide and the past discussion I feel like it is implicitly assumed that each communicator or window will have a set of associated VNIs. Then how do we determine how many VNIs to assign to a communicator? I would imagine this number would typically correspond to the number of concurrency (threads). A new CVAR and/or info hint?

**Comment by rzambre** [comment]
Following a discussion in the student meeting, it would be best to represent the VCI directly as an int instead of having the underlying netmod typedef `MPIDI_VCI_t`. MPICH could be configured with more than one netmod in which case types of `MPIDI_VCI_t` could conflict. With VCI directly defined as an int, the underlying netmod can map the integer to pointers if it needs to. This would change the APIs to the following.
```
MPIDI_NM_vci_alloc(int resource, int type, int properties,  int * vci);
MPIDI_NM_vci_free(int vci);
MPIDI_SHM_vci_alloc(int resource, int type, int properties,  int * vci);
MPIDI_SHM_vci_free(int vci);
```
This would also be consistent with the existing APIs such as the NM/SHM_progress APIs.

**Comment by rzambre** [comment]
Just a note on the hash functions. Ideally, the hash function that will be used to select a VCI for a pt2pt operation can be based on the communicator only (`COMM_ONLY`), rank only (`RANK_ONLY`), tag only (`TAG_ONLY`), or any other possible combination of the three such as `COMM_RANK`, `COMM_TAG`, `RANK_TAG`, and `COMM_RANK_TAG`. Note that each category itself can have multiple hash functions (for example, with `COMM_RANK`, the hash could be a mod operator such as `rank % #vcis_in_comm` or certain ranges of `rank` can map to different VCIs in the comm).

However, the practical use cases for hash functions based `RANK/TAG_ONLY`, or `RANK_TAG` are not known. Hence, we will simplify the choices for the basis of the hash functions to `COMM_ONLY`, `COMM_RANK`, `COMM_TAG`, and `COMM_RANK_TAG`, that is, all of them will use the `comm`. If the need arises, we can implement the infrastructure for hash functions on `rank`s and `tag`s withouth the `comm`.

**Comment by rzambre** [comment]
Currently, the understanding is that we treat the NM and SHM VCIs as separate entities. So, in the execution of an operation, we would first need to compute if it is an NM or SHM operation, after which, we will hash into either the pool of NM or SHM VCIs.

However, after some thought and a discussion with @pavanbalaji, it seems it'd be better to re-define the VCI to be a higher-level abstraction that includes NM and SHM VCIs. So, a VCI would treat NM and SHM as its attributes, just like it currently treats TX or RX to be one of its attributes. A generic VCI would then be able to perform both NM and SHM operations. We can then have specialized NM-only VCIs and/or SHM-only VCIs.

**Comment by hzhou** [comment]
This issue is now obsolete. We have shifted the VCI mapping to the lower netmod/shmmod/active-message layer. CH4 upper layer simply maintain an abstract VCI concept mainly for coordination between sub-layers and for efficient per-vci progress. The VCI pool and attributes are no longer necessary.
