### ISSUE TITLE
representing object sizes with size_t instead of MPI_Aint internally

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#3365]
Many internal MPICH interfaces use `MPI_Aint` rather than `int` to deal with object sizes > `INT_MAX`. I propose instead we convert values representing the size of objects in memory to `size_t` internally, as it is the natural fit. In the unlikely event that a system/compiler does not support `size_t`, autoconf (`AC_TYPE_SIZE_T`) will set a reasonable default.

A good place to start would be the `MPID_` interfaces (and the dataloop code). Eventually it could spread to all `MPIR` interfaces. Care will need to be taken to ensure we convert values back to `int`, `MPI_Aint`, or `MPI_Count` where necessary.

**Comment by raffenet** [comment]
Somewhat related to #3357.

**Comment by hzhou** [comment]
@pavanbalaji @raffenet   shifting the discussion to this issue:

>    I previously suggested that MPI_Aint was not an ideal choice when referring to count arguments internally in MPICH #3365. I still believe this is true, as negative counts (i.e. not displacements) are not allowed and size_t is an appropriate C language type to represent a number of bytes to be read/written/copied.

So here is the new discussion: can we make MPI_Aint unsigned? FORTRAN will still use it as signed due to the limit of the language, but as long as FORTRAN code does not make it negative -- which we could claim that is a user error -- the binding interface will hold.

PS: maybe these discussion should move to that issue :)

**Comment by hzhou** [comment]
I re-read @raffenet 's header comment, I agree that it makes sense. The only worry is the difference in the signed-ness  and all the potential compiler warnings. If we can, in the first stage, redefine MPI_Aint to `unsigned` type, then transiting to `size_t` all internally will be trivial. It will even pave the way to phase away the `MPI_Aint` type altogether -- it is a FORTRAN thing and should be confined in the binding.

**Comment by jeffhammond** [comment]
@hzhou We discussed unsigned `MPI_Aint` when we were developing MPI 3.0.  I think we decided it was just "too stupid" to add `MPI_Auint`/`MPI_Uaint` given how unlikely it is that anyone will need more than 8 exbibytes per process.

@jdinan Anything to add here?

In any case, I vigorously support using `size_t` internally and saving the conversions for the highest level entry point.  This will make MPICH source more accessible.

**Comment by hzhou** [comment]
@jeffhammond When the range of data is from zero to less than 9E18, both `int64_t` and `uint64_t` are superset of the data range, and either is sufficient. So, IMO, the standard only need specify the desired datatype -- a MPI_Aint that can be used to represent address type data -- and leave the exact detail, whether signed 64-bit, or unsigned 64-bit, or 128bit, as implementation detail. If that interpretation is valid, then, which is what I am proposing,  we could use `size_t` for the C part of MPICH, and use `integer*8` for the FORTRAN binding.

**Comment by hzhou** [comment]
> I think we decided it was just "too stupid" to add MPI_Auint/MPI_Uaint given how unlikely it is that anyone will need more than 8 exbibytes per process.

There are 32-bit or even 16-bit systems (IOT?) out there. Unless the standard decide a minimum size, the argument of "sufficient" is invalid.

**Comment by jeffhammond** [comment]
@hzhou Supporting unsigned allows one to use 2x the memory as signed.  You know what else allows one to use 2x the memory as signed?  Two MPI processes.

In the 32-bit case, you are arguing that we should make a huge change in the MPI standard to allow Fortran programs to access more than 2 but less than 4 GiB of memory when running with a single process.  That is literally the only thing you would be fixing.

I will be happy to discuss 16-bit support if MPICH has a plan to support such platforms.  You can't use Linux there (https://www.quora.com/Can-a-modern-Linux-kernel-be-compiled-to-run-on-8-bit-or-16-bit-devices-such-as-a-PIC)...

And if `MPI_Win_shared_query` pops into your head as an exception, one can use `disp_unit>1` here.

**Comment by hzhou** [comment]
@jeffhammond I am not arguing making changes in the standard to allow FORTRAN program to access above 2G. Even the C ABI allows 4G (by using `size_t`), FORTRAN binding still won't enable it. I am only arguing for a minor ABI change. But the impact -- if non of the application had problem before, and they are not using negative AINT -- will be small.

**Comment by hzhou** [comment]
If we don't want a ABI change -- until more compelling reasons come -- then we'll have to settle at the conversion (typecast) at all MPI functions. I guess I am arguing myself back. I haven't considered the ABI reasons earlier :)

**Comment by hzhou** [comment]
I think at this point I am fully in agreement with @raffenet . I'll make a PR at some point to test it out.

**Comment by hzhou** [comment]
After trying a PR replacing all (other than MPI level) MPI_Aint with `size_t`, I question the effort. Mostly it is because MPI_Aint has better range than `size_t`, for the negative side. With 64-bit, we practically never will hit the upper range, but we use the negative side very often -- as sentinels or sometimes intentionally (e.g. negative datatype extent). With `size_t`, underflow -- where two unsigned variables subtract from each other is a real danger. 

Remind me what is the original motive to suggest internally use `size_t` everywhere? If it due to those pesky `signed/unsigned` conversion warnings, I think it makes more sense to use `ssize_t` everywhere. Since we already have `MPI_Aint` defined, it makes sense to use `MPI_Aint` every where.

**Comment by pavanbalaji** [comment]
I don't think a direct search/replace will work.  In some cases we need signed integers, while in others we need unsigned.

**Comment by hzhou** [comment]
A direct search/replace of all `size_t` into `MPI_Aint` might work though. I can see the cases where we need signed integers; what is the case that we need unsigned `size_t`? One reason is to access the upper range -- it'll be between the limit of 2G or 4G. Another reason may be because `stdlib` function uses/returns `size_t`, we could do cast there, safely as long as the range is not an issue.

**Comment by pavanbalaji** [comment]
The use of `size_t` is so the compiler can catch problems when our value accidentally becomes negative.  For example, we use `MPI_Aint` to represent the size of our internal datatypes, which is unnecessary.

**Comment by hzhou** [comment]
> The use of size_t is so the compiler can catch problems when our value accidentally becomes negative. 

Certainly I wished the same, but unfortunately no. Compilers won't give you warning even if you do this:
```
size_t A;
A=-1;
```
, even under `-Wall`.

It may seem silly looking at trivial examples, but in general, the only way to do run-time range-check is to adding `asserts` when every  a variable assignment happens -- of course that will never do.

We have `MPIR_Assert(count<0)` in many places just for that purpose. That only will work with signed `MPI_Aint`. An unsigned variable will never assert to be `<0`. To add assertion that an unsigned variable underflow has occurred, on the other hand, is no where as elegant as to assert a signed one become negative.

So I think the argument of checking data not to become negative argues for a signed type.

**Comment by raffenet** [comment]
I would not recommend a search/replace of all `MPI_Aint` -> `size_t`. There are places internally where `MPI_Aint` is the type we should be using. My idea was to use `size_t` when representing the size of an object in memory. For example the underlying communication APIs for message buffers almost always take a `size_t` argument.

Also, it appears `-Wsign-conversion` can catch errors like above, but it is not part of `-Wall` for either `gcc` or `clang` at this time.
```raffenet@glitch:/tmp/ $ gcc-8 -Wsign-conversion foo.c
foo.c: In function 'main':
foo.c:6:14: warning: unsigned conversion from 'int' to 'size_t' {aka 'long unsigned int'} changes value from '-1' to '18446744073709551615' [-Wsign-conversion]
   size_t a = -1;```

**Comment by hzhou** [comment]
The warning of unsigned conversion only warns on the datatype conversion, not on the actual value overflow. In practice, we will fix those warnings by type casting. In practice, it is `size_t a = b; `, where `b` is a signed number that is *assumed* to be positive.

**Comment by jeffhammond** [comment]
`ptrdiff_t` is useful here...

**Comment by hzhou** [comment]
> `ptrdiff_t` is useful here...

which is just another alias for `MPI_Aint`, practically.

**Comment by hzhou** [comment]
As I expected, blindly replacing `size_t` with `MPI_Aint` -- in PR #3826 -- went without a glitch, and I do feel much safer now. The only place we need check is where we call other libraries that uses `size_t`, where we need to cast.

Checking back, the only reason for `size_t` and ``ptrdiff_t` is portability (provided by the language). Since we already taken care of the portability with `MPI_Aint`, it fills the bill plus the consistency.

To generalize, I think the only unsigned type C needs is `unsigned char`, where we are dealing with encodings, not really integers. When we are dealing with integers (that we are going to do arithmetic with), a signed integer is much safer to use since only the extreme values have a chance to overflow. An unsigned number only gains two times of the range and it is not worth the trade off of bringing the overflow edge right where the most common values sit. When the integer range is too small, the answer should always be to go to the next larger size or to check with your logic, rather than sacrificing the one sign-bit.

**Comment by hzhou** [comment]
After the logic, time to "appeal to authority" :) : 

* Fortran
* Java
* https://wesmckinney.com/blog/avoid-unsigned-integers/
* http://soundsoftware.ac.uk/c-pitfall-unsigned.html
* ...

Apparently it is an old wisdom.

**Comment by hzhou** [comment]
I am going to close this as we are not going to resolve the discussion. Meanwhile, we are fixing the incompatibility on a on-going basis. Linking this PR https://github.com/pmodels/mpich/pull/5069, which aims to get `-Wconversion` warnings clean.
