### ISSUE TITLE
Half-precision floating point type

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#3389]
ISO/IEC TS 18661-3:2015 defines `_FloatN` binary floating point types (including `_Float16`) for the C language. Newer versions of Clang/LLVM support this type. Other compilers may, as well.

https://clang.llvm.org/docs/LanguageExtensions.html#half-precision-floating-point

We could define something along the lines of `MPIX_C_FLOAT16` for users to experiment with when compiler support is detected.

**Comment by raffenet** [comment]
Tagging @gcongiu because we'll eventually have to test this, and may want to modify dtpools to do so.

**Comment by hzhou** [comment]
For reference, there was a long discussion in MPI Forum: https://github.com/mpi-forum/mpi-issues/issues/65

**Comment by hzhou** [comment]
I am not quite happy with the current way that using configure to filling the handle values in mpi.h. Configure do feature tests, the handle value logic should be separate from feature detection. I am pondering on whether we could even separate the type size detection from configure and having a separate script just do that. Once the compiler and flags are determined by configure, data size detection should be straightforward. We could easily add that script to Makefile and a dependency for mpi.h.

The current configure is too complex. I think we should take steps in de-complex it.

**Comment by raffenet** [comment]
I enthusiastically support the effort to make configure less complex. However, the `AC_CHECK_SIZEOF` macro is provided by autoconf and seems well-suited to this task. At the very least, the type size detection could be split into a separate file to avoid complicating the main `configure.ac`. Thoughts?

**Comment by hzhou** [comment]
I am thinking about a simple script to do the datatype configure: `make_datatypes`. It processes mpi.h.in to mpi.h, taking only environment variable CC, CFLAGS and CXX, CXXFLAGS and corresponding fortran's.  `mpi.h.in` should be a complete mpi.h with *typical* default values and `make_datatypes` double checks sizes at makefile time (as dependency) and modify if necessary. Rather than run individual AC_CHECK_SIZE, `make_datatypes` can do wholesale checking and only do individual checking for certain modern types such as complex, stdints, and _Float16 etc. That should be much faster and much less noisier as well.
