### ISSUE TITLE
ch4/ofi: `FI_ASYNC_IOV` workarounds

### ISSUE THREAD

**Issue by pavanbalaji** [pmodels/mpich#3562]
Current mpich has an arbitrary requirement of `FI_ASYNC_IOV` to be at least 3.  This makes it hard for us to add additional header components when needed (we do multiple copies in such cases).  Also, it means mpich will not work with OFI providers that do not support at least that length IOVs.

It'd be cleaner if MPICH's upper-level header management used large IOVs, but the OFI netmod serialized them to whatever the provider gives, e.g., using copies.

**Comment by hajimefu** [comment]
You should be talking about `iov_limit`, not `FI_ASYNC_IOV`.

**Comment by pavanbalaji** [comment]
I guess what I'm trying to say is that the mpich internal iov_limit can be decoupled from `FI_ASYNC_IOV`.  The internal limit should basically be infinite (which will require some refactoring).

**Comment by hzhou** [comment]
I believe the issue was a misunderstanding, or no longer true. When we need send non-contig data via IOVs, we use separate pack buffer for iov array rather than the fixed `iov[3]` in am headers. The fixed `iov[3]` are specifically for am headers and data payload, which is finite by code design. In another word, the iov_limit and FI_ASYNC_IOV is decoupled.
