### ISSUE TITLE
MPI Endpoints prototype

### ISSUE THREAD

**Issue by halimamer** [pmodels/mpich#3591]
MPI Endpoints is meant to extend the existing one-to-one mapping between MPI processes and ranks to allow an MPI process to host more than one rank that behave like a separate MPI process. This allows the MPI library to isolate network resources belonging to separate endpoints. The major motivation for doing so is to enable more parallelism in MPI communication across application threads though, to some extent, having multiple independent network resources can improve throughput of single-threaded network traffic as well.
 
The concept of MPI Endpoint has been floating around for a decade but no integrated implementation in an MPI library as been demonstrated. We are currently working on the first integrated prototype of MPI Endpoints in MPICH and this issue is meant to track progress on it and the various challenges that will be encountered along the way.

This prototype will be based on the latest iteration of the for MPI Forum proposal found at https://github.com/mpi-forum/mpi-issues/issues/56.

The first prototype (PT1) builds on top of the multi-VCI design. The is a prototype that maps community objects to VCIs at https://github.com/halimamer/mpich/tree/dirty_vcis as a reference. This prototype shows how to exploit multiple VCIs mapped to `libfabric` independent TX, RX, and CQ objects.

The second two prototypes build upon PT1 by reusing the optimized independent VCI paths (as of March 22, 2019, the master branch of MPICH has too many bottlenecks to be a practical baseline).

*Tag-based MPI Endpoints* (PT2): this prototype encodes the endpoint id in the tag space when hardware tag matching is supported; otherwise, it is sent in message headers. This was demonstrated with the OFI netmod over PSM2, achieving up to 70M message rate with 32 threads. The prototype code can be found at #3683.

*Context-based MPI Endpoints* (PT3): this prototype encodes the endpoint id as part of the context bits. This method is less intrusive to integrate into existing libraries but chews up the scarce context id bits. If the context bits can be extended in the future, this method might become viable. A PR (though less clean compared to the tag-based one) can be found at #3684 for reference.

**Comment by Bayyapu** [comment]
@halimamer I am trying to note the FY19Q2 progress. I do not see any PR attached to this issue. Could you please update the issue with the progress by attaching the PR and document references if any?

**Comment by halimamer** [comment]
@Bayyapu , progress updated

**Comment by Bayyapu** [comment]
Thank you @halimamer

**Comment by hzhou** [comment]
This is done.

**Comment by jedbrown** [comment]
@hzhou What does it mean that this is "done"? The PR (https://github.com/pmodels/mpich/pull/3683) was not merged and I don't see the symbols in MPICH. Are you aware of any endpoints implementations that are ready for friendly users? Is the Forum still interested in the concept?

**Comment by hzhou** [comment]
We should've added more comments for context. We have evaluated the endpoints proposal and decided to pursue implicit vci mapping back in 2020. Implicit vci mapping exploits the inherent parallel information within MPI-3 specification to achieve good scalability.

The forum is no longer pursuing the endpoints proposal. However, we still believe an explicit solution to address MPI+Thread has its merits. We are working on a new proposal -- MPIX Stream. The discussion -- https://github.com/pmodels/mpich/discussions/5908

Reference:
* Zambre, Rohit, Aparna Chandramowliswharan, and Pavan Balaji. "How i learned to stop worrying about user-visible endpoints and love MPI." Proceedings of the 34th ACM International Conference on Supercomputing. 2020.
* R. Zambre, D. Sahasrabudhe, H. Zhou, M. Berzins, A. Chandramowlishwaran and P. Balaji, "Logically Parallel Communication for Fast MPI+Threads Applications," in IEEE Transactions on Parallel and Distributed Systems, vol. 32, no. 12, pp. 3038-3052, 1 Dec. 2021, doi: 10.1109/TPDS.2021.3075157.

**Comment by jedbrown** [comment]
Thanks for your reply. This is very informative, though Endpoints is really what we were excited about. The issue is that we'd like to use the MPI programming model across threads within a library. But the library has callbacks to user code and implementing those callbacks in a different process (as with internal `MPI_Comm_spawn`) requires the calling application to "think MPI" and design their data structures appropriately. Meanwhile, using fork-join thread parallelism is catastrophic to performance because it's similar cost to off-node communication even for embarrassingly parallel operations. Anyway, it's kind of sad to hear Endpoints has been dropped with seemingly nothing on the horizon for this use case.

**Comment by hzhou** [comment]
@jedbrown You should check out the new MPIX stream proposal - https://arxiv.org/abs/2208.13707. It is available in the current MPICH main branch. We believe it supersedes the features in the endpoints proposal. We'd like to hear feedback from actual use cases, especially where you think the new proposal falls short.

**Comment by jedbrown** [comment]
Thanks. I think this describes the key distinction.
> A key flaw in the endpoint proposal, from our view, is the inflation of thread context into virtual processes. To a multithread
programmer, a process and a thread are separate concepts. Between threads the memory is shared, and thus there is no need for explicit data exchange. Between processes, explicit messaging is needed, and that is where MPI is used. Thus, the process concept and its identification using ranks are important. With the endpoints proposal, the process become less identifiable. Users may have to manage their own endpoint ranks to process the rank translation table. The endpoints proposal also makes interthread messages equally accessible as interprocess messages. Since users rarely need interthread messages, this inflation makes MPI more difficult to understand and use.

I don't buy the premise for a number of reasons. For one, "threaded" primitives often over-synchronize and have cost comparable or larger than off-node messaging. OpenMP doesn't provide neighbor messaging; instead you typically have every thread place a result in part of a shared data structure and use barrier synchronization. If you want the minimal synchronization available for MPI semantics, you need to write significant custom code with atomics and memory ordering. If every thread provides input to an allreduce, the reduction becomes two-stage with reduction between threads (using OpenMP or something) followed by `MPI_Allreduce` (one rank per process), then notification of delivery to the threads.

In practice, there are very few examples of libraries working well in an environment where `#pragma omp parallel` is at the top of main and threads call interfaces collectively (the minimal synchronization style) -- instead almost everyone provides sequential public APIs and instantiate the parallelism internally, with callbacks occurring inside a parallel region expected to be independent rather than collective. Note that in threaded programming, it is usually a performance best practice to expose the parallelism at the coarsest possible granularity and use partitioned data structures with minimum synchronization. MPI encourages that by default.

From what I can tell, Streams creates a big new API surface while removing one of the most attractive parts of Endpoints, which is allowing threaded programs to use MPI-style communication among threads (for convenience as well as performance). An important use case is allowing applications that were designed for threads (common among GUI apps and those not "built for HPC") to call libraries that were developed using MPI. The latter are often in a problem domain where shared-nothing is a better default, and shared memory windows or plain shared data structures between threads are available for strategic sharing.

How hard would it be for Streams to be augmented with an interface that allows a `MPI_Comm` to assign a unique rank to the `stream_comm`'s (`rank`, `idx`) pair so that normal MPI interfaces can be used to communicate among threads?

**Comment by hzhou** [comment]
I see. Originally when I wrote the quoted paragraph, I was imagining that if the user wants "shared nothing" semantics between threads, then they can simply use the "MPI-everywhere" pattern, launching multiple processes on a single node.  From your comment, I see this is impractical when the application and libraries are not co-designed.

>  instead almost everyone provides sequential public APIs and instantiates the parallelism internally, with callbacks occurring inside a parallel region expected to be independent rather than collective. 

Thanks for explaining the pattern. What you are seeking is a mechanism to create virtual MPI processes guaranteed with the shared-nothing semantics within a parallel region. This is a narrower pattern than the original endpoints proposal trying to address. In the original endpoints proposal, the virtual processes created by the endpoints communicator can easily leak. For example, we can't assume thread-local-storage or thread id if the endpoints can be used across parallel regions. And this leak spreads the complications to other parts of MPI, for example, MPI_Comm_dup etc. It is a much simpler case if we restrict the virtual process's lifetime to be within a single parallel region where the thread-virtual_process mapping is immutable and uninheritable. Let us think about it.

**Comment by hzhou** [comment]
Your example is helpful. But I am not sure I understand it yet. Let me ask some (silly) questions.

> The classic MPI+X model is to place `omp parallel` inside `linear_solver.solve` and the user can put it inside `F`. This incurs a lot of overhead

The overhead is the repeated spawn/join of threads or just repeated thread synchronization?

> If we instead put it up-front at the top of main and let the library split its communicators to one rank per thread, then the MPI-style partitioned data structures are still good inside the library.

If you put the parallel region at the top of `main`, then it is an `MPI-everywhere` pattern, right? Sounds like an endpoints communicator with its lifetime with parallel region should work here, right?

> But sometimes the time loop is going to do things (c.prepare() above) that are not appropriate inside a parallel region. Sure, the app can probably use omp single for that stuff, but some will really want to have omp parallel at that level, opening it each time step to call the nonlinear solver.

I am confused by this paragraph. `c.prepare` can't work inside a parallel region, right? Then, here are you saying the only permissible pattern is to have parallel region inside each time step, whether or not one wants?

**Comment by jedbrown** [comment]
Thanks, I'm happy to discuss.

> The overhead is the repeated spawn/join of threads and the repeated thread synchronization?

Yes. Note that threading systems usually have pools so it's not really creating a new OS thread, but it still needs to hand off work, which involves some communication primitives that usually scale worse than log(T) where T is the number of threads.

> If you put the parallel region at the top of main, then it is an MPI-everywhere pattern, right? Sounds like an endpoints communicator with its lifetime within parallel region should work here, right?

Yes, though possibly error-prone since that constraint would need to be conveyed to user code written by people unfamiliar with MPI.

> `c.prepare` can't work inside a parallel region, right?

It might be able to use `omp single` if the author is familiar with that, but let's assume it can't.

> Then here, are you saying the only permissible pattern is to have parallel region inside each time step, whether or not one wants? Aren't we back with the classic MPI+X pattern earlier?

The nonlinear solve iteration (`while (!converged)`) would be running inside a parallel region and calling `F` inside that region. If creation of the parallel region moved _inside_ the nonlinear or linear solver, then we'd be specializing on the threading model (OMP, TBB, etc.) and since the linear solver is likely also a public interface, the API would generally need to be split into the versions that do parallelism inside and the versions that assume they're called collectively (MPI-style) inside a parallel region. The nesting goes really deep in practice so this can be really disruptive and error-prone. It's also often the case that an application calls different libraries that create their owns work threads (because one library uses OMP, another uses TBB) and this leads to accidental oversubscription and thus poor user experience (they usually don't know what oversubscription is, just that the code is way slower sometimes). So I consider it desirable to help applications deal with threads on the outside and make libraries that reliably just use whatever threads they're given, agnostic of how those threads were created.

**Comment by hzhou** [comment]
Ok, I think I get it. The parallel region is in `NonlinearSolver::solve(...)` but outside the `while(!converged)`. `self.F` is a user callback function. You would like `F` to take a communicator but is ignorant of whether it is being called inside a thread-parallel context or process-parallel context. Am I close?

In this case, the endpoints communicator is created at the start of `solve` and destroyed at the end of `solve`, right?

I am confused that your other description seems to want to move the parallel region outside the `for (t: times)` loop, but it is prevented by the semantics of `c.prepare(t, u)`. What is your suggested solution and how is that to do with the endpoints proposal?
