### ISSUE TITLE
Problem with MPI_File_set_view

### ISSUE THREAD

**Issue by MrSmile** [pmodels/mpich#3903]
I've encountered this problem with [MSMPI](https://github.com/microsoft/Microsoft-MPI/issues/17), but after switching to ubuntu with
`mpicc for MPICH version 3.3a2`
I'm able to reproduce the same behaviour too.

[Test Case](https://gist.github.com/MrSmile/39ba76cda0e66d9f63842287321613b2)

After `mpiexec -n 4 ./test` I'm expecting file `test.txt` with content `::::ABCDabcd` but instead get segfault. And even single-node run hung up.

Is that intended and reverse-order datatypes is not supported or it's a bug?

**Comment by wkliao** [comment]
I found  2 problems in your test program.
1. MPI_LB is deprecated since MPI standard 2.0. Try replace it with MPI_BYTE in your test program.
2. values in offsets[] will create a filetype whose displacements are not in a monotonically nondecreasing order, which violates the MPI standard requirement. See MPI standard 3.1, Chapter 13.1.1, page 492.

Compiled with MPICH 3.3, your test program should spew an error message below.
```
MPI error: Other I/O error , error stack:
ADIO_Set_view(48):  **iobadoverlap displacements of filetype must be in a monotonically nondecreasing order
```

**Comment by hzhou** [comment]
@MrSmile It appears this is the issue with your test case. Could you confirm? Should we close this issue?

**Comment by MrSmile** [comment]
Yes, random offsets are not supported by the standard (but some implementations do work in that case), so my test was wrong.
