### ISSUE TITLE
configure errors when AC_CHECK_SIZEOF fails

### ISSUE THREAD

**Issue by pavanbalaji** [pmodels/mpich#3910]
If `AC_CHECK_SIZEOF` fails to detect the size of a datatype, the error propagates throughout the code and ends up with the following unintelligible error message:

```
error: Unable to convert MPI_SIZEOF_AINT to a hex string.  This is either because
we are building on a very strange platform or there is a bug somewhere in configure.
```

For at least one user, the problem was that the `LD_LIBRARY_PATH` was not set for some dependency library, so configure thought the `sizeof(void *)` was zero.  We should throw an error message when `AC_CHECK_SIZEOF` detects a size of zero for any datatype.

**Comment by hzhou** [comment]
I already have a PR revamp the configure datatype detection - PR #3819. Among multiple items, it consolidates `AC_CHECK_SIZEOF` (as otherwise it gets cached by the first call), moves the builtin datatype handle logic back to `mpi.h.in`, moves all hexcode conversion into `AC_CONFIG_COMMAND`, as well as addressing the `crossfile` generation. It is kind of big, so need volunteers to review it.

**Comment by pavanbalaji** [comment]
PR #3819 mixes a lot of unrelated changes.
