### ISSUE TITLE
mpir: Support context_id bits > 16

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#4063]
Context id values are currently limited to 16 bits. https://github.com/pmodels/mpich/blob/master/src/include/mpir_contextid.h#L11-L13

There have been requests to increase the context id space from multiple downstream libraries. This ticket is to track progress on a more flexible context id representation.

**Comment by wesbland** [comment]
The CH4/OFI netmod at least should be able to handle this without too much trouble by changing a couple of fields around here:

https://github.com/pmodels/mpich/blob/3b84e79871f4b7a1b4d39b004b14be5318d9cb08/src/mpid/ch4/netmod/ofi/ofi_capability_sets.h#L119

and here:

https://github.com/pmodels/mpich/blob/3b84e79871f4b7a1b4d39b004b14be5318d9cb08/src/mpid/ch4/netmod/ofi/ofi_capability_sets.h#L145

**Comment by hzhou** [comment]
That is 65536 communicators, right?

**Comment by wesbland** [comment]
> That is 65536 communicators, right?

Not really. In practice it's at least 65536/3 because we reserve some additional context IDs for each communicator. There's also the problem of actually finding a context ID that everyone in the group can agree on (which I believe was the subject of a paper by @jdinan a while back IIRC). So it actually end up being a lot less than 64K.

**Comment by raffenet** [comment]
http://www.mcs.anl.gov/~balaji/pubs/2012/eurompi/eurompi12.ctxid.pdf

**Comment by hzhou** [comment]
fixed by #4102
