### ISSUE TITLE
/bin/sh version of the mpicc mistreats quotes and attempts array expansion

### ISSUE THREAD

**Issue by jxy** [pmodels/mpich#4171]
```
$ mpicc -show -DT="'a'" -DT="'\""
cc  \"-DT='a'\" '-DT='"' -lmpi
```

there's also the erroneous array expansion, `"${allargs[@]}"`, at https://github.com/pmodels/mpich/blob/c99bb8d563ee374beb652bf0af812931bbe0773d/src/env/mpicc.sh.in#L264-L266

**Comment by raffenet** [comment]
@jxy after the changes in #4184:
```
mpicc -show -DT="'a'" -DT="'\""
gcc -DT='a' -DT='" <...>
```
I believe this is the expected output. Can you confirm?

**Comment by jxy** [comment]
I'm not set up for testing, but here is a quick unit test for you.
```
echo "main(){char n=N,d=D,q=Q,l=L;P(n);P(d);P(q);P(l);}" |
mpicc -DP=putchar -DN="'N'" -DD="'\"'" -DQ="'\\''" -DL="'\\n'" -w -x c - && ./a.out
```

**Comment by raffenet** [comment]
Looks good to me.
```
echo "main(){char n=N,d=D,q=Q,l=L;P(n);P(d);P(q);P(l);}" |
./mpicc -DP=putchar -DN="'N'" -DD="'\"'" -DQ="'\\''" -DL="'\\n'" -w -x c - && ./a.out
N"'
```

**Comment by jxy** [comment]
Great!  Let's convince ourselves with an elaborate unit test:

```
echo "main(){P(a);P(b);P(c);P(d);P(e);P(f);P(g);P(h);P(i);P(j);S(s);}" |
mpicc -DP=putchar -DS=puts \
-Da="'\$'" -Db="'('" -Dc="'<'" -Dd="' '" -De="'Y'" -Df="'!'" -Dg="'\\''" -Dh="'\"'" -Di="'\`'" -Dj="'\\n'" \
-Ds="\"\$(< Y!'\\\"\`\"" -w -x c - &&
./a.out
```

**Comment by hzhou** [comment]
The issue is with `mpicc.sh` (the portable shell script, vs. the bash script), and when an argument contains both single quote and double quote, the simplistic approach -- assumes the argument won't have both quotation marks simultaneously -- fails.

The bash version is immune to this as bash have extensions that properly handle arrays and can properly quote individual argument.

The ultimate fix for the shell script may be to detect the case when an arg contains both types of quotation marks and use escape (\) to escape the single quote while using double quote -- probably using `sed`.

**Comment by hzhou** [comment]
Okay, I am going to give it another try. The offending lines are:
```
    # -----------------------------------------------------------------
    # Other arguments.  We are careful to handle arguments with
    # quotes (we try to quote all arguments in case they include
    # any spaces)
*\"*)
qarg="'"$arg"'"
;;
*\'*)
qarg='\"'"$arg"'\"'
;;
*)
qarg="'$arg'"
;;
```
The rule of thumb is 1. can't use double quote since it contains too many unsafe chars. 2. single quotes need be singled out.
