### ISSUE TITLE
Info Hints Need a Device-Level Callback Function

### ISSUE THREAD

**Issue by wesbland** [pmodels/mpich#4440]
There is not currently a clean way for the device to be notified about a communicator info hint changing value. The way this is currently done (in `MPIR_Comm_hint_init`) is to just take a callback function, but there is no way for that callback function to not be legally callable from the `MPIR` layer. 

https://github.com/pmodels/mpich/blob/c726c3cdc7a518abb8c1de0089e2e080bf1af049/src/mpi/comm/commutil.c#L158-L168

So I think we probably need a new ADI function to allow the device (and netmod/shmmod) to be able to pick up on new hints that would get called after the `MPIR` layer is done.

**Comment by hzhou** [comment]
The callback function is used when a device wants to create a custom hint. 

Currently, device can check any hints inside the `comm_commit_hook`. If the hint value is non-zero, then user has set a hint; otherwise, the device can potentially customize the default hint.

`MPI_Comm_set_info` probably also need to invoke a device hook so the device can do the same check.

**Comment by wesbland** [comment]
Yeah, my thinking is that communicator creation should just call this function too to make things cleaner.
