### ISSUE TITLE
Potential ABI changes

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#4838]
Now that `main` branch is targeting MPICH 4.0 development, it is a good time to consider ABI changes in MPICH. This issue will be the place to aggregate things we would like to change, and the reasons why, so they can be considered by members of the MPICH ABI Compatibility Initiative.

- Update MPI_Status struct definition
  - Simplify count hi/lo and cancelled fields.
- Increase MPI_MAX_INFO_VAL
  - Allow for more information in a single info hint, e.g. for RMA optimizations.

**Comment by ddurnov** [comment]
Just would like to highlight that we were keeping ABI compatibility since 2014 https://www.mpich.org/abi/
What kind of value we get from the ABI changes?

Simplification of the fields doesn't feel like has enough weight vs a possibility to migrate between MPICH derived implementation w/o applicaiton recompilation.

We may think about compatibility mode/layer which would allow our users to avoid recompilation but if it will be only on Intel MPI level only (we will have to keep compatibility on our product anyway), then it will break whole idea of the ABI initiative. It means that we will have to have bindings or something like that in order to be compatible with new MPICH from ABI perspective. Would be great if we could avoid it.

Anyway, would be great if we could analyze what kind of value we get from the changes and what kind of stuff could be optional so we could keep some form of migration mechanisms in place if the value from the changes is high.

**Comment by raffenet** [comment]
> Anyway, would be great if we could analyze what kind of value we get from the changes and what kind of stuff could be optional so we could keep some form of migration mechanisms in place if the value from the changes is high.

@ddurnov agreed. I created this issue with the idea that we can edit it over time and come up with a detailed list of changes people might want to see in the ABI, backed up with use-cases and analysis. The currently listed changes, IMO, do not yet make a good case for breakage.

**Comment by hzhou** [comment]
The consensus is to resist *any* ABI changes unless there is compelling reasons -- i.e. these isn't work around or with significant performance improvement.

Closing this issue for now.

**Comment by raffenet** [comment]
We should keep a list of these somewhere. It doesn't have to be an issue. Should we use a Github wiki page? Notes file?

**Comment by hzhou** [comment]
> We should keep a list of these somewhere. It doesn't have to be an issue. Should we use a Github wiki page? Notes file?

Either is fine with me.

**Comment by raffenet** [comment]
Created https://github.com/pmodels/mpich/wiki/ABI-Change-Wishlist.
