### ISSUE TITLE
mpi4: info query

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4917]
link:
* https://github.com/mpi-forum/mpi-issues/issues/63

It seems we don't need do anything for this issue. Will close once confirmed.

**Comment by shintaro-iwasaki** [comment]
I checked the discussion.  It seems that basically the change implied by the discussion forces the existing MPI implementation (e.g., `MPI_Comm_info_get()`) to return either ...
1. an exact value that was passed by the user (e.g., `MPI_Comm_info_set()`) if it is not ignored by the implementation, or
2. `NULL` (i.e., MPI_Info does not contain such a key) if it is ignored by the implementation.

According to the discussion, it seems that the runtime should return `auto` if the user passed `auto` even if internally it is interpreted as say `1024`.
- It means that the runtime should return `"1"` if the user passed `"1"` even if internally it is interpreted as `true`.
- For the same reason, it means that the runtime should return `"  1024 "` if the user passed `"  1024 "` even if internally it is interpreted as `1024`.

There are three choices to work on this issue:
1. Save an original string as well as a real internal hint value in `MPI_Comm` (by using a linked list etc, of course, with `malloc()`).  That's heavy.
2. Reject a value that does not strictly follow our expected format (e.g., reject `"1"` and only accept `"true"` if it is `MPIR_COMM_HINT_TYPE_BOOL`).
3. Ignore such a corner case since no one cares such details. If so, we don't need to do any.

@hzhou, could you check if my interpretation is correct (especially because I cannot really check the diff of the MPI standard draft)?  Do you have any suggestion?  Or basically is the solution 1 okay?

**Comment by hzhou** [comment]
For the `set_info`:
<img width="961" alt="image" src="https://user-images.githubusercontent.com/1496702/103680987-899feb80-4f4c-11eb-828f-4526551d6c99.png">

For the `get_info`:
<img width="828" alt="image" src="https://user-images.githubusercontent.com/1496702/103681082-a5a38d00-4f4c-11eb-8ec5-d19e9ec7ba6f.png">

**Comment by shintaro-iwasaki** [comment]
@hzhou Thanks a lot!

**Comment by shintaro-iwasaki** [comment]
Yes, according to the spec, the runtime should return `"1"` if the user passed `"1"` even if internally the runtime accepts it as `true`. For the same reason, it means that the runtime should return `"  1024 "` if the user passed `"  1024 "` even if MPICH accepts this as `1024`.

Does the solution 1 (save every user's hint string in addition to the actually used `int` value) look okay?

**Comment by hzhou** [comment]
> 
> 
> Yes, according to the spec, the runtime should return `"1"` if the user passed `"1"` even if internally the runtime accepts it as `true`. For the same reason, it means that the runtime should return `" 1024 "` if the user passed `" 1024 "` even if MPICH accepts this as `1024`.
> 
> Does the solution 1 (save every user's hint string in addition to the actually used `int` value) look okay?

That is pedantic to the point of making both "user" and "implementor"'s life miserable 😨 

I would strongly try to "do nothing". @shintaro-iwasaki Could you cite the words and reasoning that would argue "do nothing" breaks the standard?

cc @raffenet

**Comment by hzhou** [comment]
As I read the discussions, it has always about whether the implementation can change the "*semantic*" values  of an info key to the more restrictive semantic meaning. There is nothing about whether user says 1, we reply "Yay, true". I.e. that is not a sematic change. Besides, I don't think the discussion is even about that, it is more about if the previous info hints value is "false", now the user want to info set to "true", should the implementation change the value to true or ignore the user request.

**Comment by shintaro-iwasaki** [comment]
I still believe it should return the original value as it is. From the users' perspective, if the value is changed (even if equivalence is obvious for humans), it is hard to programmatically check if the value is accepted or not especially because it is returned by "string".

Implementing this change is not a big deal (just creating a linked list or something), but I also agree that this change is not very beneficial for both users and developers as @hzhou said. If we interpret "semantics" of values, yes it makes sense.

I am okay to fix this, but if the current behavior is fine for others, I will keep the current implementation and close this issue.
