### ISSUE TITLE
mpi4: deprecate MPI_T_ERR_INVALID_ITEM

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#4918]
link:
* https://github.com/mpi-forum/mpi-issues/issues/60

**Comment by shintaro-iwasaki** [comment]
I'd like to ask an acceptable solution for this issue.

### Background

An error code `MPI_T_ERR_INVALID_ITEM` has been inadvertently added but this meaning is the same as `MPI_T_ERR_INVALID_INDEX`, so `MPI_T_ERR_INVALID_ITEM` should be "deprecated".  At present only `MPI_T_enum_get_item()` uses this error code in MPICH.

#### Solution 1: change `MPI_T_enum_get_item()` to return `MPI_T_ERR_INVALID_INDEX` instead of `MPI_T_ERR_INVALID_ITEM`.

If so, the following existing code does not work.
```c
// MPICH-4 will return INVALID_INDEX!
if (MPI_T_enum_get_item(...) == MPI_T_ERR_INVALID_ITEM)
  [...];
```
This leaves `MPI_T_ERR_INVALID_ITEM` as it is.  Just unused.

#### Solution 2: make `MPI_T_ERR_INVALID_ITEM` as an alias of `MPI_T_ERR_INVALID_INDEX`.

If so, the following existing code works.
```c
// MPICH-4 will return INVALID_INDEX but INVALID_INDEX == INVALID_ITEM
if (MPI_T_enum_get_item(...) == MPI_T_ERR_INVALID_ITEM)
  [...];
```
This breaks the ABI compatibility, though.

---

I believe few people really care the error code of `MPI_T_enum_get_item()` (at most they check if it is MPI_SUCCESS or not).  Solution 1 looks sufficient to me, but is Solution 2 (or any other possible solution) preferred?

**Comment by hzhou** [comment]
The MPICH 4.0 is expected to create a new ABI.
