### ISSUE TITLE
testing: run mpi4py testsuite against mpich

### ISSUE THREAD

**Issue by hzhou** [pmodels/mpich#5159]
We should set up nightly/weekly tests for a few selected applications/libraries. It will help us discover more potential bugs/issues. It will also shorten the cycle of frequent bug-report-diagnosis-retry cycles. We'll start with `mpi4py`  -- thanks to the suggestion and offer to help by @dalcinl and @leofang. ref: https://github.com/pmodels/mpich/issues/5149

**Comment by hzhou** [comment]
Just checked out [mpi4py](https://github.com/mpi4py/mpi4py). First obstacle --
```
python test_datatype.py
Traceback (most recent call last):
  File "test_datatype.py", line 44, in <module>
    class TestDatatype(unittest.TestCase):
  File "test_datatype.py", line 330, in TestDatatype
    @unittest.skipMPI('openmpi', MPI.CHARACTER.Get_size() == 0)
  File "mpi4py/MPI/Datatype.pyx", line 79, in mpi4py.MPI.Datatype.Get_size
mpi4py.MPI.Exception: Invalid datatype, error stack:
internal_Type_size_x(69): MPI_Type_size_x(MPI_DATATYPE_NULL, size=0x7ffe53740bd0) failed
internal_Type_size_x(40): Datatype for argument datatype is a null datatype
```

MPICH sets the datatype to `MPI_DATATYPE_NULL` when it is not available. And calling `MPI_Type_size_x(MPI_DATATYPE_NULL, ...)` is an error. 

@leofang @dalcinl This line `@unittest.skipMPI('openmpi', MPI.CHARACTER.Get_size() == 0)` is the offending line. How do we do `@unittest.skipMPI(`mpich`, MPI_CHARACTER == MPI_DATATYPE_NULL)`?

**Comment by dalcinl** [comment]
OK, so this is a relatively recent change, right? The fix is trivial:

```python
@unittest.skipMPI(mpich, MPI.CHARACTER == MPI.DATATYPE_NULL)
```

PS: FYI, mpi4py's API is very close to the old C++ bindings.

**Comment by dalcinl** [comment]
Actually, the proper way should be the following:

```python
@unittest.skipMPI('mpich', MPI.CHARACTER == MPI.DATATYPE_NULL)
@unittest.skipMPI('openmpi', MPI.CHARACTER != MPI.DATATYPE_NULL and MPI.CHARACTER.Get_size() == 0)
```

This way the testsuite adjusts to the idiosyncrasies of both MPICH and Open MPI.

**Comment by hzhou** [comment]
> OK, so this is a relatively recent change, right?

Setting unavailable datatype to `MPI_DATATYPE_NULL` has always been in mpich. It is a behavior I personally not fond of. The issues only arise when I try to test MPICH build without Fortran binding. Thanks for the tip.

**Comment by hzhou** [comment]
> 
> 
> Actually, the proper way should be the following:
> 
> ```python
> @unittest.skipMPI('mpich', MPI.CHARACTER == MPI.DATATYPE_NULL)
> @unittest.skipMPI('openmpi', MPI.CHARACTER == MPI.DATATYPE_NULL or MPI.CHARACTER.Get_size() == 0)
> ```
> 
> This way the testsuite adjusts to the idiosyncrasies of both MPICH and Open MPI.

I think there is another issue that I am having. How does `mpi4py` knows it is running MPICH`? I think the very issue is the check with 'openmpi' got run in the first place.

**Comment by dalcinl** [comment]
You are right, now I remember! I stopped testing special builds (without Fortran, without ROMIO, etc) gong ago. The testsuite kept evolving, mostly to workaround Open MPI bugs popping up release after release.

PS: Setting unavailable datatypes to `MPI_DATATYPE_NULL` is IMHO a good compromise, certainly much better than having a non-NULL but otherwise nonfunctional handle (like Open MPI does).

**Comment by dalcinl** [comment]
> How does `mpi4py` knows it is running MPICH`?

The `skipMPI()` decorator is implemented in `test/mpiunittest.py`. It uses the `MPI.get_vendor()` function, something I added long before `MPI.Get_library_version()` was added to the standard.

**Comment by dalcinl** [comment]
@hzhou Have you ever used Python's unitest framework? You can run the test scripts individually, pass `-v` for more verbose output, and also pass `TestClassName.testMethodName` to narrow down what you run. That's particularly useful while debugging and fixing stuff.

```shell
python test/test_datatype.py -v TestDatatype.testCommit
```

Another way to do it is the following. You use the runtests.py script, with `--include` and a regex for the test scripts name to run, and again, if you want to narrow even more,  `TestClassName.testMethodName`. This runtests.py script is not standard, just something that I added to enable/disable some mpi4py-related things.

```shell
python test/runtests.py -v --include 'test_datatype$'  TestDatatype.testCommit
```

**Comment by dalcinl** [comment]
Did you notice that I edited my comment? My initial one contained wrong code, and that's what you probably got in your email.

> I think the very issue is the check with 'openmpi' got run in the first place.

That should not be a problem. Python's `or` operator shorts circuit, so if the datatype is really null, the `Get_size()` method should not be called. Please note that these checks for NULL are executed before the `skipMPI()` has its chance of checking that you are actually running MPICH.

If this is giving you too much of a headache, just rename the test method as `xtestWhatever()` (such that the initial name is not "test"), and Python's unittest will ignore it.

**Comment by hzhou** [comment]
> That should not be a problem. Python's `or` operator shorts circuit, so if the datatype is really null, the `Get_size()` method should not be called. Please note that these checks for NULL are executed before the `skipMPI()` has its chance of checking that you are actually running MPICH.

That's the understanding I am missing. Thanks.

**Comment by hzhou** [comment]
@dalcinl With PR #5161, I am able to pass the tests clean. Two notes:
* `test_datatype - testMatchSize`
   -> `@unittest.skipMPI('openmpi', MPI.CHARACTER == MPI.DATATYPE_NULL or MPI.CHARACTER.Get_size() == 0)`
   Passing invalid datatype `MPI_DATATYPE_NULL` to mpich is ok although the test didn't do much.

* `test_pack - testPackUnpackExternal`
  This one need skip the invalid datatype (or `MPI_DATATYPE_NULL`).

**Comment by leofang** [comment]
@hzhou Sorry for missing the fun here...I should have mentioned sooner that mp4ipy supports CUDA-aware MPI. If you install CuPy and/or Numba you can run the demo in https://github.com/mpi4py/mpi4py/tree/master/demo/cuda-aware-mpi. Our test suite also has GPU tests, ex: `mpiexec -n 2 python test/runtests.py --cupy`. Please give it a shot when you have time. 

I expect this to be a bumpier journey than the CPU tests, because it does't seem easy to get MPI+CUDA right --- I've seen too many tests hanging and/or segfaults, across different MPI implementations and versions, and most of the time there's a bug in the MPI implementation. I've played with Open MPI and MVAPICH2, but not MPICH, though.

**Comment by hzhou** [comment]
@leofang Sounds great. I'll give it try at some point.

**Comment by dalcinl** [comment]
@hzhou Current main is not OK. Is there any open PR that I'm missing?
https://github.com/mpi4py/mpi4py-testing/runs/2178191176?check_suite_focus=true

**Comment by hzhou** [comment]
> 
> 
> @hzhou Current main is not OK. Is there any open PR that I'm missing?

Yes, this one was split during review: https://github.com/pmodels/mpich/pull/5168

**Comment by leofang** [comment]
@hzhou Quick questions on MPICH's CUDA support: 
1. Looking at the `configure` file, I suppose same as in Open MPI, MPICH doesn't care which CUDA version it is built against/run on, as long as it's fairly recent (9.2+)? 
2. Why is `libmpi.so` and other shared libraries linked to `libcuda`/`libcudart`? Aren't they `dlopen`'d at runtime?
https://github.com/pmodels/mpich/blob/dec6cee8e7f2c9f2b600b7b9af6f58ac583bc4d8/src/mpl/src/gpu/mpl_gpu_cuda.c#L302-L305
3. Is there a flag/config file to disable/opt-out the CUDA support by default (but can be turned on at launch time if requested)?

I tried looking into MPICH's documentation but didn't find anything...

Background for my questions: On [conda-forge/openmpi-feedstock](https://github.com/conda-forge/openmpi-feedstock), we utilize this nice property to build Open MPI's CUDA support using any valid CUDA builder we have (current pick is 10.2), and allow users to turn on CUDA awareness at launch time if needed via setting `--mca opal_cuda_support 1`, with any CUDA version locally visible (CF has CUDA 9.2-11.2). This makes the packaging and distributing so much easy. 

I plan to do the same thing for [conda-forge/mpich-feedstock](https://github.com/conda-forge/mpich-feedstock), so that we have CUDA-aware MPI across Conda-Forge, but I need to ensure the same trick can be applied to MPICH too.

**Comment by hzhou** [comment]
> 
> 
> @hzhou Quick questions on MPICH's CUDA support:
> 
>     1. Looking at the `configure` file, I suppose same as in Open MPI, MPICH doesn't care which CUDA version it is built against/run on, as long as it's fairly recent (9.2+)?

We haven't check what is the oldest version that we depend on yet. So for now, the answer is yes -- until user reports or we discover otherwise.

> 
>     2. Why is `libmpi.so` and other shared libraries linked to `libcuda`/`libcudart`? Aren't they `dlopen`'d at runtime?
>        https://github.com/pmodels/mpich/blob/dec6cee8e7f2c9f2b600b7b9af6f58ac583bc4d8/src/mpl/src/gpu/mpl_gpu_cuda.c#L302-L305
> 

The current main support of gpu is actually coming from `yaksa`, which I think it is linked at compile time. The mechanism for mpich is not `dlopen` the library. The code you are quoting is to inject cuda memory hooks as an optional optimization. As such, it is currently not depend on by the rest of the code.

>     3. Is there a flag/config file to disable/opt-out the CUDA support by default (but can be turned on at launch time if requested)?
> 

For the main branch, you can configure with `--without-cuda` to disable cuda at compile time. At runtime, user can set environment `MPIR_CVAR_ENABLE_GPU=0` to disable it. The latter is a work-in-progress, so it does not work perfectly yet, but any time now :) 
> 
> I tried looking into MPICH's documentation but didn't find anything...
>

I know. Sorry about that. First develop, then document. We are still bound at the first stage.

**Comment by dalcinl** [comment]
@hzhou Using `--with-pm=gforker`, name publishing is not working. While I understand that there is no much point on supporting publish/lookup for gforker, perhaps there is a quick way to make the MPI publish/lookup calls fail with error rather than deadlock?

https://github.com/mpi4py/mpi4py-testing/runs/2191431467?check_suite_focus=true
https://github.com/mpi4py/mpi4py-testing/runs/2191431490?check_suite_focus=true
https://github.com/mpi4py/mpi4py-testing/runs/2191431522?check_suite_focus=true

**Comment by hzhou** [comment]
> 
> 
> @hzhou Using `--with-pm=gforker`, name publishing is not working. While I understand that there is no much point on supporting publish/lookup for gforker, perhaps there is a quick way to make the MPI publish/lookup calls fail with error rather than deadlock?

Sounds reasonable. I'll take a look.

**Comment by hzhou** [comment]
@dalcinl Could you try configure `gforker` along with the option `--with-namepublisher=file`?

**Comment by dalcinl** [comment]
@hzhou It worked like a charm! https://github.com/mpi4py/mpi4py-testing/actions/runs/689281040

Is there any way to make this work automatically? I guess the real problem is `--with-pm=hydra:gforker` or `--with-pm=gforker:hydra`, if hydra is involved (even if listed second), you may want to keep PMI as the nameserver.

At least you you could do the following: if only `pm=gforker` is requested, then make `namepublisher=file` the default.

**Comment by hzhou** [comment]
I guess we can (should) let gforker return PMI error rather than abort
