### ISSUE TITLE
Shared Memory Question

### ISSUE THREAD

**Issue by cesarpomar** [pmodels/mpich#5223]
I know that MPI_Win_create allow to perform shared memory RMA operations. I have an application than use gather and send to exchange data between process and I want to know that if all process are in the same host, will mpich perform any shared memory optimization over the communicator? or it uses the default communication like TCP. If there are some optimizations, how I can check that two nodes are connected over shared memory?

**Comment by hzhou** [comment]
MPICH will use shared memory optimization whenever possible unless it is explicitly disabled, e.g. with `MPIR_CVAR_NOLOCAL=1`. The best way to ensure the processes are on the same node is to use `MPI_Comm_split_type(comm, split_type=MPI_COMM_TYPE_SHARED, ...)`. The resulting comm will be guaranteed to be able to create and use shared memory.

**Comment by minsii** [comment]
As Hui suggested, you can first use `MPI_COMM_TYPE_SHARED` to determine if shared memory is enabled on your machine. `shm_size` will be the number of processes existing in the same shared memory domain.
```
    MPI_Comm_split_type(MPI_COMM_WORLD, MPI_COMM_TYPE_SHARED, rank, MPI_INFO_NULL, &shm_comm);
    MPI_Comm_rank(shm_comm, &shm_rank);
    MPI_Comm_size(shm_comm, &shm_size);
```

In MPICH ch4/ofi build (if you configure with `--with-device=ch4:ofi`), we enable shared memory optimization for RMA whenever possible. There are three levels of optimizations:
- RMA over `win_create`: we use `POSIX` shared memory based active-message (usually **two copies** are involved per RMA data transfer) for each RMA operation if the target process is not the origin process itself; otherwise it will be a simple memcpy.
- RMA over `win_create` with XPMEM:  If MPICH found `XPMEM` on your machine, we use XPMEM-based direct copy for each RMA operation (**single copy**). You can set `--with-ch4-shmmods=posix,xpmem --with-xpmem=[PATH]` to enable it explicitly.
- RMA over `win_allocate`: no matter XPMEM exists or not, we enable direct copy (**single copy**)for each RMA operation. This is because MPICH internally allocates the window memory, so that we can allocate it from shared memory on each process.

If you build with ch4/ucx, the above MPICH-level optimizations are not enabled by default. We let the low-level UCX do shared-memory optimizations (e.g., similar XPMEM-based optimization).

If you want to get the best performance of RMA over shared memory, we encourage you use `win_allocate` instead of `win_create`, as MPICH can control the memory location of the window buffer for better optimization :-)

**Comment by cesarpomar** [comment]
Thank you both so much, I use ch4:ofi.

If I have understood correctly, first I must use MPI_Comm_split_type to select process in the same host. Then I must to use MPI_Win_allocate to shared memory between all local process.

Has the Memory to be MPI_Alloc_mem or can I use malloc? My application has internal buffers with malloc and it would be a bit difficult to change.

If I use MPI_send over the resulting split communicator, will it use sockets or shared memory?

**Comment by minsii** [comment]
If you use `MPI_Win_allocate`, the window buffer is internally allocated by this call. It does not accept pre-allocated buffer.

If you have to use `malloc` to allocate the buffers, then just use `MPI_Win_create`. The RMA will go through POSIX shared memory, still faster than socket.

**Comment by cesarpomar** [comment]
Thanks
