### ISSUE TITLE
Improve support for `mpi_minimum_memory_alignment` info hint

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#5694]
The way MPICH currently implements `mpi_minimum_memory_alignment` is to take the requested alignment from the user and add it to the size of the allocation, then manually align after the fact. In MPL, we have `MPL_aligned_alloc` which uses an alignment aware allocator (e.g. `posix_memalign`) and will fail if the requested allocation cannot be granted. This should be straightforward to integrate to alignment requests from the user and could reduce the dependance on manual alignment.

See relevant function: https://github.com/pmodels/mpich/blob/main/src/mpid/ch4/src/ch4_init.c#L601

**Comment by raffenet** [comment]
Edited the description to reflect the fact that MPICH currently manually aligns the allocation for the user. So the request is honored, but potentially at the cost of extra memory allocation.

**Comment by hzhou** [comment]
How do we deal with the case when `MPL_aligned_alloc` fails due to both `aligned_alloc` and `posix_memalign` being unavailable?

**Comment by raffenet** [comment]
> How do we deal with the case when `MPL_aligned_alloc` fails due to both `aligned_alloc` and `posix_memalign` being unavailable?

We could fallback to `malloc` and manual alignment like we have now. In fact, we could put that fallback code in MPL. But we would have to do some work to also make it work for device allocations as the current ch4 code does. Its not as straightforward as I originally assumed 😞.

**Comment by hzhou** [comment]
> > How do we deal with the case when `MPL_aligned_alloc` fails due to both `aligned_alloc` and `posix_memalign` being unavailable?
> 
> We could fallback to `malloc` and manual alignment like we have now. In fact, we could put that fallback code in MPL. But we would have to do some work to also make it work for device allocations as the current ch4 code does. Its not as straightforward as I originally assumed 😞.

We have to manage the pointer in order to use the fallback manual alignment. The current `MPL_free` is just `free` without memory tracing options, so it won't work generally. Currently `MPL_aligned_alloc` isn't being used anywhere probably due to this fallback concern. Since we currently only needed in `MPI_Alloc_mem`, I think it is better to keep the code as now rather than complicate with the dependency on `MPL_aligned_alloc`. When we have additional use case, we can refactor then.

**Comment by hzhou** [comment]
@travisk1154 Could you take care of this issue? Here is what need to be done: refactor `MPID_Alloc_mem` in 
https://github.com/pmodels/mpich/blob/main/src/mpid/ch4/src/ch4_init.c#L601 to --
```
#ifdef MPL_DEFINE_ALIGNED_ALLOC
[use `MPL_aligned_alloc`]
#else 
[use the current code that does many adjustment]
#endif
```

**Comment by hzhou** [comment]
@raffenet Revisiting this issue and I think I am leaning toward closing it without changing the current code. Since we need to support multiple `buf_type`, we'll need to maintain the hash lookups for each memory we allocate. Since we already have this hash lookup of metadata, using `MPL_aligned_alloc` does not save much complexity -- in fact, it adds complexity since we still need worry about the fallback path.

**Comment by raffenet** [comment]
I'm OK with closing it. I underestimated how much the current code was doing when I wrote the issue, so it's probably not worth the trouble.
