### ISSUE TITLE
ABI question: MPI_Count and MPI_Offset on MacOS and Linux

### ISSUE THREAD

**Issue by jeffhammond** [pmodels/mpich#6412]
These types are part of the ABI and compilers get angry when one mixes pointers to `long` and `long long` even though both are 8 bytes on 64-bit Linux and MacOS.

Is there a reason why MPICH chooses `long` versus `long long` here?

MacOS
```
typedef long MPI_Aint;
typedef long long MPI_Count;
typedef long long MPI_Offset;
```

Linux
```
typedef long MPI_Aint;
typedef long MPI_Count;
typedef long MPI_Offset;
```

**Comment by hzhou** [comment]
I think that is the behavior changes over MPICH versions rather than the difference between Linux and MacOS. The earlier versions let ROMIO to decide what to use for `MPI_Offset`, which accidentally checks `long long` before `long`. The MPICH main configure checks `long` before `long long`.  So the older MPICH versions have these annoyances you observed.  The later MPICH version fixes it.

**Comment by jeffhammond** [comment]
Thanks.  This is good to know.
