### ISSUE TITLE
dimsCreate member function of MPIR_Process

### ISSUE THREAD

**Issue by tks2004** [pmodels/mpich#7053]
Is dimsCreate always set to NULL. is there a case where it is not null and if not null where is the defnition or to which other function is it pointing it to

**Comment by hzhou** [comment]
MPICH is a vendor architecture, that allows a vendor to supply or override specific implementations from within the device layer. The `dimsCreate` pointer is one of such support mechanism. For example, a vendor can set `dimsCreate` to a custom implementation in `MPID_Init`, then MPICH will use it instead of the implementation in `MPIR_Dims_create_impl`. So with upstream MPICH and most vendor MPICHs, the `dimsCreate` remain null. But it is possible for some vendors to change it.
